### model
model_name_or_path: ./base_model/Qwen2.5-7B-Instruct-Uncensored

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 32
lora_target: all
deepspeed: ./scripts/configs/deepspeed/ds_z0_config.json

### dataset
dataset: safe_emails_1000, set1_dataset, set1_dataset_nophishing
template: alpaca
cutoff_len: 1024
max_samples: 4000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: ./output/qwen2_lora32_set1
logging_steps: 10
save_steps: 400
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 0.0002
num_train_epochs: 100
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true
ddp_timeout: 180000000

remake_tokens_flag: False
ref_model_dir: 
classification_flag: False
classification_dir: 
phishing_type: email
model_type: qwen2
### eval
# val_size: 0.0
# per_device_eval_batch_size: 1
# evaluation_strategy: steps
# eval_steps: 500
